zmq_input_address: "ipc:///tmp/batch_manager/result"
zmq_output_address: "ipc:///tmp/task_manager/result"
gpu_all: [1]

models:
  ports:
    sender_open_addr: 5556
    sender_sync_addr: 5555
    receiver_open_addr: 5546
    receiver_sync_addr: 5545
  zmq_config:
    sndhwm: 10
    rcvhwm: 10
    sndtimeo: 3600000
    rcvtimeo: 3600000


  
