zmq_input_address: "ipc:///tmp/batch_manager/result"
zmq_output_address: "ipc:///tmp/task_manager/result"

docker_registry: "https://registry.visionhub.ru"
docker_login: "admin"
docker_password: "6y4JgtsaNbDvQVCX"

gpu_all: [1, 2, 3, 4]
