# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/inferresult.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import outputinfer_pb2 as protos_dot_outputinfer__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/inferresult.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18protos/inferresult.proto\x1a\x18protos/outputinfer.proto\"N\n\x0bInferResult\x12\r\n\x05model\x18\x01 \x01(\t\x12\x11\n\tsource_id\x18\x02 \x01(\t\x12\x1d\n\x07outputs\x18\x03 \x03(\x0b\x32\x0c.OutputInferb\x06proto3'
  ,
  dependencies=[protos_dot_outputinfer__pb2.DESCRIPTOR,])




_INFERRESULT = _descriptor.Descriptor(
  name='InferResult',
  full_name='InferResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='InferResult.model', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source_id', full_name='InferResult.source_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='InferResult.outputs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=132,
)

_INFERRESULT.fields_by_name['outputs'].message_type = protos_dot_outputinfer__pb2._OUTPUTINFER
DESCRIPTOR.message_types_by_name['InferResult'] = _INFERRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InferResult = _reflection.GeneratedProtocolMessageType('InferResult', (_message.Message,), {
  'DESCRIPTOR' : _INFERRESULT,
  '__module__' : 'protos.inferresult_pb2'
  # @@protoc_insertion_point(class_scope:InferResult)
  })
_sym_db.RegisterMessage(InferResult)


# @@protoc_insertion_point(module_scope)
