# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/inferdata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/inferdata.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16protos/inferdata.proto\"7\n\tInferData\x12\x13\n\x0bpayload_int\x18\x01 \x03(\x05\x12\x15\n\rpayload_float\x18\x02 \x03(\x01\x62\x06proto3'
)




_INFERDATA = _descriptor.Descriptor(
  name='InferData',
  full_name='InferData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload_int', full_name='InferData.payload_int', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload_float', full_name='InferData.payload_float', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['InferData'] = _INFERDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InferData = _reflection.GeneratedProtocolMessageType('InferData', (_message.Message,), {
  'DESCRIPTOR' : _INFERDATA,
  '__module__' : 'protos.inferdata_pb2'
  # @@protoc_insertion_point(class_scope:InferData)
  })
_sym_db.RegisterMessage(InferData)


# @@protoc_insertion_point(module_scope)
