# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/inputinferrequest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import inferdata_pb2 as protos_dot_inferdata__pb2
from protos import parametermessage_pb2 as protos_dot_parametermessage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/inputinferrequest.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1eprotos/inputinferrequest.proto\x1a\x16protos/inferdata.proto\x1a\x1dprotos/parametermessage.proto\"\xcc\x01\n\x11InputInferRequest\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\x10\n\x08\x64\x61tatype\x18\x02 \x01(\t\x12\x18\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\n.InferData\x12\x36\n\nparameters\x18\x04 \x03(\x0b\x32\".InputInferRequest.ParametersEntry\x1a\x44\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.ParameterMessage:\x02\x38\x01\x62\x06proto3'
  ,
  dependencies=[protos_dot_inferdata__pb2.DESCRIPTOR,protos_dot_parametermessage__pb2.DESCRIPTOR,])




_INPUTINFERREQUEST_PARAMETERSENTRY = _descriptor.Descriptor(
  name='ParametersEntry',
  full_name='InputInferRequest.ParametersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='InputInferRequest.ParametersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='InputInferRequest.ParametersEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=294,
)

_INPUTINFERREQUEST = _descriptor.Descriptor(
  name='InputInferRequest',
  full_name='InputInferRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape', full_name='InputInferRequest.shape', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datatype', full_name='InputInferRequest.datatype', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='InputInferRequest.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='InputInferRequest.parameters', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_INPUTINFERREQUEST_PARAMETERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=294,
)

_INPUTINFERREQUEST_PARAMETERSENTRY.fields_by_name['value'].message_type = protos_dot_parametermessage__pb2._PARAMETERMESSAGE
_INPUTINFERREQUEST_PARAMETERSENTRY.containing_type = _INPUTINFERREQUEST
_INPUTINFERREQUEST.fields_by_name['data'].message_type = protos_dot_inferdata__pb2._INFERDATA
_INPUTINFERREQUEST.fields_by_name['parameters'].message_type = _INPUTINFERREQUEST_PARAMETERSENTRY
DESCRIPTOR.message_types_by_name['InputInferRequest'] = _INPUTINFERREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputInferRequest = _reflection.GeneratedProtocolMessageType('InputInferRequest', (_message.Message,), {

  'ParametersEntry' : _reflection.GeneratedProtocolMessageType('ParametersEntry', (_message.Message,), {
    'DESCRIPTOR' : _INPUTINFERREQUEST_PARAMETERSENTRY,
    '__module__' : 'protos.inputinferrequest_pb2'
    # @@protoc_insertion_point(class_scope:InputInferRequest.ParametersEntry)
    })
  ,
  'DESCRIPTOR' : _INPUTINFERREQUEST,
  '__module__' : 'protos.inputinferrequest_pb2'
  # @@protoc_insertion_point(class_scope:InputInferRequest)
  })
_sym_db.RegisterMessage(InputInferRequest)
_sym_db.RegisterMessage(InputInferRequest.ParametersEntry)


_INPUTINFERREQUEST_PARAMETERSENTRY._options = None
# @@protoc_insertion_point(module_scope)
