batch_manager_address: ipc:///tmp/batch_manager/input
debatch_manager_address: ipc:///tmp/debatch_manager/result
model_storage_address: ipc:///tmp/model_storage

listen_address: "tcp://*:7787"
send_address: "tcp://*:7788"
