# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  unit-tests-lint-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: actions/cache@v2
      name: cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        mypy --install-types
    - name: Test with pytest
      run: ./entrypoint.sh TEST
    - name: Check with mypy
      run: ./entrypoint.sh MYPY
    - name: Coverage
      run: ./entrypoint.sh COVERAGE
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
        
        
