# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  pull_request:
    branches: "*"

jobs:
  unit-tests-lint-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv venv
        source venv/bin/activate
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Cache
      uses: actions/cache@v2.1.6
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: venv
        # An explicit key for restoring and saving the cache
        key: venv
    - name: Test with pytest
      run: ./entrypoint.sh TEST
    - name: Check with mypy
      run: ./entrypoint.sh MYPY
    - name: Coverage
      run: ./entrypoint.sh COVERAGE
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
        
        
